ALTER TABLE public.jcfpm_items
  ADD COLUMN IF NOT EXISTS item_type text NOT NULL DEFAULT 'likert',
  ADD COLUMN IF NOT EXISTS payload jsonb,
  ADD COLUMN IF NOT EXISTS assets jsonb;

INSERT INTO public.jcfpm_items (id, dimension, subdimension, prompt, reverse_scoring, sort_order, item_type, payload) VALUES
('D7.1', 'd7_cognitive_reflection', 'Cognitive Reflection', 'Míček a pálka stojí 110 Kč. Pálka stojí o 100 Kč více než míček. Kolik stojí míček?', false, 73, 'mcq', '{"options":[{"id":"a","label":"5 Kč"},{"id":"b","label":"10 Kč"},{"id":"c","label":"15 Kč"},{"id":"d","label":"20 Kč"}],"correct_id":"a"}'),
('D7.2', 'd7_cognitive_reflection', 'Logic Puzzle', '5 strojů vyrobí 5 součástek za 5 minut. Kolik součástek vyrobí 100 strojů za 100 minut?', false, 74, 'mcq', '{"options":[{"id":"a","label":"100"},{"id":"b","label":"500"},{"id":"c","label":"2000"},{"id":"d","label":"10000"}],"correct_id":"c"}'),
('D7.3', 'd7_cognitive_reflection', 'Percent Change', 'Zvýšíš cenu o 25 % a následně ji snížíš o 20 %. Výsledek vůči původní ceně je:', false, 75, 'mcq', '{"options":[{"id":"a","label":"vyšší"},{"id":"b","label":"nižší"},{"id":"c","label":"stejný"},{"id":"d","label":"nelze určit"}],"correct_id":"c"}'),
('D7.4', 'd7_cognitive_reflection', 'Data Reasoning', 'Model má 99% přesnost, ale pozitivní případy tvoří jen 1 % dat. Nejpravděpodobnější problém je:', false, 76, 'mcq', '{"options":[{"id":"a","label":"Přesnost je zavádějící kvůli nevyváženým třídám"},{"id":"b","label":"Model má příliš nízký recall"},{"id":"c","label":"Data jsou vždy kvalitní"},{"id":"d","label":"Model je perfektní"}],"correct_id":"a"}'),
('D7.5', 'd7_cognitive_reflection', 'Logical Fallacy', 'Který argument je klam "post hoc"?', false, 77, 'mcq', '{"options":[{"id":"a","label":"Po změně logo stouply prodeje, logo tedy způsobilo růst."},{"id":"b","label":"Pokud prší, je mokro. Prší, takže je mokro."},{"id":"c","label":"Všichni, koho znám, to dělají, takže je to správné."},{"id":"d","label":"Pokud A, tak B. Neplatí B, takže neplatí A."}],"correct_id":"a"}'),
('D7.6', 'd7_cognitive_reflection', 'Logic', 'Platí: Pokud A ⇒ B a B je pravdivé. Co můžeme říct o A?', false, 78, 'mcq', '{"options":[{"id":"a","label":"A musí být pravdivé"},{"id":"b","label":"A může, ale nemusí být pravdivé"},{"id":"c","label":"A je určitě nepravdivé"},{"id":"d","label":"Nelze nic říct o B"}],"correct_id":"b"}'),

('D8.1', 'd8_digital_eq', 'Tone Reading', 'Kolega po delší diskusi napíše jen: "Ok." Jaká je nejlepší reakce?', false, 79, 'scenario_choice', '{"options":[{"id":"a","label":"Ignoruji to, je to potvrzení."},{"id":"b","label":"Doptám se, zda je vše v pořádku nebo něco chybí."},{"id":"c","label":"Pošlu dlouhé vysvětlení bez otázky."}],"correct_id":"b"}'),
('D8.2', 'd8_digital_eq', 'Conflict Chat', 'Klient píše: "Tohle je zklamání." Co odpovíš?', false, 80, 'scenario_choice', '{"options":[{"id":"a","label":"To je nespravedlivé."},{"id":"b","label":"Mrzí mě to. Můžeš upřesnit, co konkrétně nefunguje?"},{"id":"c","label":"Vysvětlím, proč je to tak."}],"correct_id":"b"}'),
('D8.3', 'd8_digital_eq', 'Async Team', 'Po incidentu je v chatu ticho. Co uděláš?', false, 81, 'scenario_choice', '{"options":[{"id":"a","label":"Počkám, až to někdo otevře."},{"id":"b","label":"Otevřu krátké check-in vlákno a nabídnu podporu."},{"id":"c","label":"Pošlu technické logy bez komentáře."}],"correct_id":"b"}'),
('D8.4', 'd8_digital_eq', 'Onboarding', 'Nováček se v asynchronním týmu ztrácí. Jak pomůžeš?', false, 82, 'scenario_choice', '{"options":[{"id":"a","label":"Pošlu mu odkazy bez kontextu."},{"id":"b","label":"Vytvořím krátký kontext + nabídnu čas na dotazy."},{"id":"c","label":"Řeknu, ať se zeptá někoho jiného."}],"correct_id":"b"}'),
('D8.5', 'd8_digital_eq', 'Feedback', 'Potřebuješ dát kritickou zpětnou vazbu v textu. Nejlepší postup je:', false, 83, 'scenario_choice', '{"options":[{"id":"a","label":"Napsat jen chybu bez kontextu."},{"id":"b","label":"Popis faktů + dopad + nabídka řešení."},{"id":"c","label":"Napsat veřejně do kanálu."}],"correct_id":"b"}'),
('D8.6', 'd8_digital_eq', 'Tone Shift', 'Kolega odpoví krátce a sarkasticky. Co je vhodné?', false, 84, 'scenario_choice', '{"options":[{"id":"a","label":"Ignorovat tón a pokračovat v tématu."},{"id":"b","label":"Doptat se v soukromí, zda je vše ok."},{"id":"c","label":"Reagovat stejně sarkasticky."}],"correct_id":"b"}'),

('D9.1', 'd9_systems_thinking', 'Systems Mapping', 'Přiřaď změnu k nejpravděpodobnějšímu dopadu.', false, 85, 'drag_drop', '{"sources":[{"id":"s1","label":"Zvýšení ceny"},{"id":"s2","label":"Zkrácení doby dodání"},{"id":"s3","label":"Vyšší kvalita podpory"}],"targets":[{"id":"t1","label":"Pokles poptávky"},{"id":"t2","label":"Růst spokojenosti"},{"id":"t3","label":"Vyšší loajalita"}],"correct_pairs":[{"source":"s1","target":"t1"},{"source":"s2","target":"t2"},{"source":"s3","target":"t3"}]}'),
('D9.2', 'd9_systems_thinking', 'Bottleneck', 'Zrychlíš jednu část procesu, ale další zůstane stejná. Co hrozí?', false, 86, 'mcq', '{"options":[{"id":"a","label":"Zlepšení všech metrik"},{"id":"b","label":"Bottleneck v navazující části"},{"id":"c","label":"Snížení variability"},{"id":"d","label":"Bez vlivu"}],"correct_id":"b"}'),
('D9.3', 'd9_systems_thinking', 'System Flow', 'Seřaď tok v systému.', false, 87, 'ordering', '{"options":[{"id":"o1","label":"Vstup"},{"id":"o2","label":"Zpracování"},{"id":"o3","label":"Výstup"},{"id":"o4","label":"Zpětná vazba"}],"correct_order":["o1","o2","o3","o4"]}'),
('D9.4', 'd9_systems_thinking', 'Secondary Effects', 'Přiřaď změnu k vedlejšímu efektu.', false, 88, 'drag_drop', '{"sources":[{"id":"s1","label":"Vyšší marketingové výdaje"},{"id":"s2","label":"Snížení chybovosti"},{"id":"s3","label":"Zvýšení fluktuace"}],"targets":[{"id":"t1","label":"Růst poptávky"},{"id":"t2","label":"Nižší reklamace"},{"id":"t3","label":"Ztráta know-how"}],"correct_pairs":[{"source":"s1","target":"t1"},{"source":"s2","target":"t2"},{"source":"s3","target":"t3"}]}'),
('D9.5', 'd9_systems_thinking', 'Feedback Loop', 'Který signál nejvíce ukazuje posilující zpětnou vazbu?', false, 89, 'mcq', '{"options":[{"id":"a","label":"Růst uživatelů zvyšuje doporučení, což zvyšuje další růst"},{"id":"b","label":"Vyšší cena snižuje poptávku"},{"id":"c","label":"Více testů snižuje počet chyb"},{"id":"d","label":"Nižší latence zlepšuje UX"}],"correct_id":"a"}'),
('D9.6', 'd9_systems_thinking', 'Impact Check', 'Po změně jedné části systému bys měl ověřit:', false, 90, 'mcq', '{"options":[{"id":"a","label":"Jen lokální metriku"},{"id":"b","label":"Dopady na navazující části a dlouhodobé efekty"},{"id":"c","label":"Názor nejhlasitější osoby"},{"id":"d","label":"Vůbec nic"}],"correct_id":"b"}'),

('D10.1', 'd10_ambiguity_interpretation', 'Ambiguity Visual', 'Na abstraktním obrazu vidíš jako první:', false, 91, 'image_choice', '{"options":[{"id":"a","label":"Riziko"},{"id":"b","label":"Příležitost"},{"id":"c","label":"Nejasný signál"}],"correct_id":"b"}'),
('D10.2', 'd10_ambiguity_interpretation', 'Ambiguity Visual', 'Nejasný trend na trhu v tobě vyvolá spíše:', false, 92, 'image_choice', '{"options":[{"id":"a","label":"Nutnost brzdit"},{"id":"b","label":"Chuť experimentovat"},{"id":"c","label":"Vyčkávání"}],"correct_id":"b"}'),
('D10.3', 'd10_ambiguity_interpretation', 'Ambiguity Visual', 'Při prvním pohledu na nejasný signál volíš:', false, 93, 'image_choice', '{"options":[{"id":"a","label":"Ověřit rizika"},{"id":"b","label":"Hledat příležitosti"},{"id":"c","label":"Ignorovat"}],"correct_id":"b"}'),
('D10.4', 'd10_ambiguity_interpretation', 'Ambiguity Visual', 'V situaci bez jasných dat je pro tebe přirozenější:', false, 94, 'image_choice', '{"options":[{"id":"a","label":"Bezpečný rámec"},{"id":"b","label":"Rychlý průzkum"},{"id":"c","label":"Nečinnost"}],"correct_id":"b"}'),
('D10.5', 'd10_ambiguity_interpretation', 'Ambiguity Visual', 'Když nejsou jasné instrukce, první interpretace je:', false, 95, 'image_choice', '{"options":[{"id":"a","label":"Potenciální hrozba"},{"id":"b","label":"Potenciální růst"},{"id":"c","label":"Náhoda"}],"correct_id":"b"}'),
('D10.6', 'd10_ambiguity_interpretation', 'Ambiguity Visual', 'Nejasný signál vnímáš spíše jako:', false, 96, 'image_choice', '{"options":[{"id":"a","label":"Riziko"},{"id":"b","label":"Příležitost"},{"id":"c","label":"Šum"}],"correct_id":"b"}'),

('D11.1', 'd11_problem_decomposition', 'Decomposition', 'Seřaď kroky pro vytvoření MVP.', false, 97, 'ordering', '{"options":[{"id":"o1","label":"Definovat cíl"},{"id":"o2","label":"Stanovit hypotézy"},{"id":"o3","label":"Postavit prototyp"},{"id":"o4","label":"Otestovat"},{"id":"o5","label":"Iterovat"}],"correct_order":["o1","o2","o3","o4","o5"]}'),
('D11.2', 'd11_problem_decomposition', 'Planning', 'Přiřaď úkol k fázi projektu.', false, 98, 'drag_drop', '{"sources":[{"id":"s1","label":"Zmapovat potřeby uživatelů"},{"id":"s2","label":"Navrhnout řešení"},{"id":"s3","label":"Nasadit MVP"}],"targets":[{"id":"t1","label":"Discovery"},{"id":"t2","label":"Design"},{"id":"t3","label":"Build"}],"correct_pairs":[{"source":"s1","target":"t1"},{"source":"s2","target":"t2"},{"source":"s3","target":"t3"}]}'),
('D11.3', 'd11_problem_decomposition', 'Incident Response', 'Seřaď kroky při řešení incidentu.', false, 99, 'ordering', '{"options":[{"id":"o1","label":"Stabilizovat službu"},{"id":"o2","label":"Diagnostikovat příčinu"},{"id":"o3","label":"Opravit"},{"id":"o4","label":"Post-mortem"}],"correct_order":["o1","o2","o3","o4"]}'),
('D11.4', 'd11_problem_decomposition', 'Structuring', 'Co je nejlepší první krok u vágního zadání?', false, 100, 'mcq', '{"options":[{"id":"a","label":"Hned začít realizovat"},{"id":"b","label":"Ujasnit cíl a kritéria úspěchu"},{"id":"c","label":"Přidat více lidí"},{"id":"d","label":"Počkat na instrukce"}],"correct_id":"b"}'),
('D11.5', 'd11_problem_decomposition', 'AI Workflow', 'Přiřaď artefakt k vrstvě promptování.', false, 101, 'drag_drop', '{"sources":[{"id":"s1","label":"Základní pravidla a role"},{"id":"s2","label":"Konkrétní požadavek"},{"id":"s3","label":"Kritéria hodnocení"}],"targets":[{"id":"t1","label":"System"},{"id":"t2","label":"User"},{"id":"t3","label":"Evaluation"}],"correct_pairs":[{"source":"s1","target":"t1"},{"source":"s2","target":"t2"},{"source":"s3","target":"t3"}]}'),
('D11.6', 'd11_problem_decomposition', 'Prioritization', 'Seřaď kroky pro rozklad složitého úkolu.', false, 102, 'ordering', '{"options":[{"id":"o1","label":"Definovat výsledek"},{"id":"o2","label":"Rozdělit na části"},{"id":"o3","label":"Seřadit podle dopadu"},{"id":"o4","label":"Přiřadit odpovědnosti"}],"correct_order":["o1","o2","o3","o4"]}'),

('D12.1', 'd12_moral_compass', 'Ethics', 'Získáš citlivá data, která mohou zlepšit model, ale uživatel s tím nesouhlasil. Co uděláš?', false, 103, 'scenario_choice', '{"options":[{"id":"a","label":"Použiji je, protože pomohou"},{"id":"b","label":"Požádám o souhlas nebo data nepoužiji"},{"id":"c","label":"Použiji je anonymně bez informování"}],"correct_id":"b"}'),
('D12.2', 'd12_moral_compass', 'Integrity', 'Tým chce zamlčet slabinu produktu před klientem. Jak se zachováš?', false, 104, 'scenario_choice', '{"options":[{"id":"a","label":"Souhlasím, hlavně že se uzavře deal"},{"id":"b","label":"Navrhnu otevřeně pojmenovat riziko a nabídnout řešení"},{"id":"c","label":"Neřeším to"}],"correct_id":"b"}'),
('D12.3', 'd12_moral_compass', 'Fairness', 'Algoritmus zvyšuje konverze, ale znevýhodňuje část uživatelů. Co uděláš?', false, 105, 'scenario_choice', '{"options":[{"id":"a","label":"Nechám to, pokud roste výkon"},{"id":"b","label":"Zastavím nasazení a hledám férovější variantu"},{"id":"c","label":"Skryji metriky"}],"correct_id":"b"}'),
('D12.4', 'd12_moral_compass', 'Transparency', 'Zjistíš chybu ve výpočtu odměn, která ti krátkodobě pomáhá. Co uděláš?', false, 106, 'scenario_choice', '{"options":[{"id":"a","label":"Nechám to být"},{"id":"b","label":"Nahlásím chybu"},{"id":"c","label":"Počkám, jestli si toho někdo všimne"}],"correct_id":"b"}'),
('D12.5', 'd12_moral_compass', 'Pressure', 'Manažer tlačí na rychlé vypuštění funkce bez bezpečnostního auditu. Co zvolíš?', false, 107, 'scenario_choice', '{"options":[{"id":"a","label":"Vypustím to"},{"id":"b","label":"Zastavím a navrhnu minimální audit"},{"id":"c","label":"Přehodím odpovědnost na jiný tým"}],"correct_id":"b"}'),
('D12.6', 'd12_moral_compass', 'Whistleblowing', 'Všimneš si systematického zkreslení dat. Jak postupuješ?', false, 108, 'scenario_choice', '{"options":[{"id":"a","label":"Ignoruji, není to moje věc"},{"id":"b","label":"Zvednu téma a navrhnu nápravu"},{"id":"c","label":"Pošlu to anonymně bez dalšího"}],"correct_id":"b"}')
ON CONFLICT (id) DO UPDATE SET
  dimension = EXCLUDED.dimension,
  subdimension = EXCLUDED.subdimension,
  prompt = EXCLUDED.prompt,
  reverse_scoring = EXCLUDED.reverse_scoring,
  sort_order = EXCLUDED.sort_order,
  item_type = EXCLUDED.item_type,
  payload = EXCLUDED.payload,
  assets = EXCLUDED.assets;
