CREATE TABLE IF NOT EXISTS public.jcfpm_items (
  id text PRIMARY KEY,
  dimension text NOT NULL,
  subdimension text,
  prompt text NOT NULL,
  reverse_scoring boolean DEFAULT false,
  sort_order integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS jcfpm_items_dimension_idx
ON public.jcfpm_items (dimension, sort_order);

CREATE TABLE IF NOT EXISTS public.job_role_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  d1 double precision NOT NULL,
  d2 double precision NOT NULL,
  d3 double precision NOT NULL,
  d4 double precision NOT NULL,
  d5 double precision NOT NULL,
  d6 double precision NOT NULL,
  salary_range text,
  growth_potential text,
  ai_impact text,
  remote_friendly text,
  weights jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS job_role_profiles_title_idx
ON public.job_role_profiles (title);

CREATE TABLE IF NOT EXISTS public.jcfpm_results (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  raw_responses jsonb NOT NULL,
  dimension_scores jsonb NOT NULL,
  fit_scores jsonb,
  ai_report jsonb,
  version text NOT NULL DEFAULT 'jcfpm-v1'
);

CREATE INDEX IF NOT EXISTS jcfpm_results_user_idx
ON public.jcfpm_results (user_id, created_at DESC);


INSERT INTO public.jcfpm_items (id, dimension, subdimension, prompt, reverse_scoring, sort_order) VALUES
('D1.1', 'd1_cognitive', 'Analytické myšlení', 'Před rozhodnutím potřebuji analyzovat všechna dostupná data a čísla.', false, 1),
('D1.2', 'd1_cognitive', 'Intuitivní myšlení', 'Často se rozhoduji na základě intuice a prvního dojmu.', true, 2),
('D1.3', 'd1_cognitive', 'Preference pro strukturu', 'Preferuji detailní plány a jasnou strukturu při řešení úkolů.', false, 3),
('D1.4', 'd1_cognitive', 'Improvizace', 'Nejlépe mi to jde když můžu improvizovat a přizpůsobovat se situaci.', true, 4),
('D1.5', 'd1_cognitive', 'Detail-orientace', 'Rád/a se věnujem detailům a přesnosti ve své práci.', false, 5),
('D1.6', 'd1_cognitive', 'Big picture', 'Zaměřuji se spíše na celkový obraz a strategii než na jednotlivé detaily.', true, 6),
('D1.7', 'd1_cognitive', 'Systematický přístup', 'Když řeším problém systematicky procházím každý krok.', false, 7),
('D1.8', 'd1_cognitive', 'Spontánnost', 'Nejlepší řešení mi často přijdou spontánně bez dlouhého přemýšlení.', true, 8),
('D1.9', 'd1_cognitive', 'Preference pro pravidla', 'Mám rád/a jasně definované postupy a pravidla.', false, 9),
('D1.10', 'd1_cognitive', 'Experimentování', 'Vyhovuje mi prostředí kde není vše pevně dané a můžu experimentovat.', true, 10),
('D1.11', 'd1_cognitive', 'Analytická náročnost', 'Baví mě číst komplexní analýzy a statistiky.', false, 11),
('D1.12', 'd1_cognitive', 'Zkušenostní rozhodování', 'Více než na fakta spoléhám na své zkušenosti a pocity.', true, 12),
('D2.1', 'd2_social', 'Solo práce', 'Nejlépe pracuji když můžu být většinu času sám/sama.', true, 13),
('D2.2', 'd2_social', 'Team collaboration', 'Prospívám v prostředí kde intenzivně spolupracuji s ostatními.', false, 14),
('D2.3', 'd2_social', 'Leadership drive', 'Rád/a přebírám vedoucí roli v týmových projektech.', false, 15),
('D2.4', 'd2_social', 'Team member preference', 'Cítím se nejlépe jako člen týmu ne jako lídr.', true, 16),
('D2.5', 'd2_social', 'External communication', 'Baví mě pracovat s klienty a externími partnery.', false, 17),
('D2.6', 'd2_social', 'Internal focus', 'Preferuji práci na vnitřních projektech bez interakce s externími lidmi.', true, 18),
('D2.7', 'd2_social', 'Collaborative initiative', 'Často přicházím s nápady které pak tým společně rozvíjí.', false, 19),
('D2.8', 'd2_social', 'Independent work', 'Raději pracuji na vlastních projektech bez nutnosti koordinace s ostatními.', true, 20),
('D2.9', 'd2_social', 'Leadership ability', 'Mám přirozenou schopnost motivovat a vést ostatní.', false, 21),
('D2.10', 'd2_social', 'Individual accountability', 'Vyhovuje mi práce kde za své výsledky odpovídám jen sám/sama sobě.', true, 22),
('D2.11', 'd2_social', 'Team communication', 'Důležitá je pro mě pravidelná komunikace a výměna informací s kolegy.', false, 23),
('D2.12', 'd2_social', 'External networking', 'Často navazuji pracovní vztahy s lidmi mimo mou organizaci.', false, 24),
('D3.1', 'd3_motivational', 'Autonomie', 'Je pro mě zásadní mít svobodu rozhodovat o tom jak pracuji.', false, 25),
('D3.2', 'd3_motivational', 'Struktura', 'Preferuji prostředí s jasnými pravidly a očekáváními.', true, 26),
('D3.3', 'd3_motivational', 'Mastery goals', 'Motivuje mě neustálé zlepšování a rozvoj nových dovedností.', false, 27),
('D3.4', 'd3_motivational', 'Performance goals', 'Důležitější je pro mě dosáhnout výsledku než se zdokonalovat v procesu.', true, 28),
('D3.5', 'd3_motivational', 'Intrinsic motivation', 'Práce mě naplňuje sama o sobě bez ohledu na odměnu.', false, 29),
('D3.6', 'd3_motivational', 'Extrinsic motivation', 'Finanční odměna a uznání jsou pro mě klíčové motivátory.', true, 30),
('D3.7', 'd3_motivational', 'Experimentální autonomie', 'Rád/a experimentuji a hledám nové způsoby práce bez vnějšího tlaku.', false, 31),
('D3.8', 'd3_motivational', 'Strukturovaná guidance', 'Nejlépe mi vyhovuje struktura s jasným vedením a zadavateli.', true, 32),
('D3.9', 'd3_motivational', 'Learning orientation', 'Baví mě učit se nové věci i když to hned nepřinese výsledky.', false, 33),
('D3.10', 'd3_motivational', 'Goal orientation', 'Zaměřuji se na konkrétní cíle a měřitelné výsledky.', true, 34),
('D3.11', 'd3_motivational', 'Intrinsic satisfaction', 'Nejsilnější motivace pro mě přichází z vnitřního uspokojení z práce.', false, 35),
('D3.12', 'd3_motivational', 'External validation', 'Potřebuji vnější uznání a zpětnou vazbu abych se cítil/a motivován/a.', true, 36),
('D4.1', 'd4_energy', 'Sprint pattern', 'Nejlépe pracuji ve sprintech s vysokou intenzitou a následným odpočinkem.', false, 37),
('D4.2', 'd4_energy', 'Steady state', 'Preferuji konstantní stabilní tempo práce po celý den.', true, 38),
('D4.3', 'd4_energy', 'Multitasking', 'Bez problému zvládám pracovat na více věcech najednou.', false, 39),
('D4.4', 'd4_energy', 'Deep work', 'Nejlépe se soustředím když se věnuji jen jedné úloze najednou.', true, 40),
('D4.5', 'd4_energy', 'Urgency performance', 'V krizových situacích a pod časovým tlakem podávám nejlepší výkony.', false, 41),
('D4.6', 'd4_energy', 'Stress sensitivity', 'Stres a urgence mě vyčerpávají a narušují mou výkonnost.', true, 42),
('D4.7', 'd4_energy', 'Intensity cycling', 'Mám rád/a intenzivní periody po kterých si můžu odpočinout.', false, 43),
('D4.8', 'd4_energy', 'Consistent load', 'Vyhovuje mi pravidelný režim s minimálními výkyvy v zátěži.', true, 44),
('D4.9', 'd4_energy', 'Task switching', 'Umím efektivně přepínat mezi různými úkoly během dne.', false, 45),
('D4.10', 'd4_energy', 'Focus blocks', 'Potřebuji dlouhé bloky času pro hlubokou soustředěnou práci.', true, 46),
('D4.11', 'd4_energy', 'Adaptability speed', 'Dokážu rychle reagovat na nečekané změny a požadavky.', false, 47),
('D4.12', 'd4_energy', 'Predictability preference', 'Nejlépe pracuji v předvídatelném prostředí s minimem překvapení.', true, 48),
('D5.1', 'd5_values', 'Sociální impact', 'Je pro mě důležité aby má práce měla pozitivní dopad na společnost.', false, 49),
('D5.2', 'd5_values', 'Individuální focus', 'Zaměřuji se hlavně na svůj osobní růst a úspěch.', true, 50),
('D5.3', 'd5_values', 'Innovation orientation', 'Přitahuje mě práce na nových inovativních projektech.', false, 51),
('D5.4', 'd5_values', 'Stability preference', 'Cením si stability a ověřených postupů.', true, 52),
('D5.5', 'd5_values', 'Contribution value', 'Práce pro mě má smysl když pomáhám druhým nebo přispívám ke společnému cíli.', false, 53),
('D5.6', 'd5_values', 'Achievement value', 'Smysl pro mě znamená dosahovat osobních milníků a úspěchů.', true, 54),
('D5.7', 'd5_values', 'Change orientation', 'Zajímá mě práce která posouvá hranice a mění status quo.', false, 55),
('D5.8', 'd5_values', 'Proven methods', 'Preferuji osvědčené metody s předvídatelnými výsledky.', true, 56),
('D5.9', 'd5_values', 'Direct impact', 'Chci aby moje práce měla viditelný dopad na životy konkrétních lidí.', false, 57),
('D5.10', 'd5_values', 'Personal achievement', 'Největší naplnění cítím když dosáhnu náročných osobních cílů.', true, 58),
('D5.11', 'd5_values', 'Relational value', 'Kvalitní vztahy s kolegy a týmem jsou pro mě zdrojem smyslu v práci.', false, 59),
('D5.12', 'd5_values', 'Instrumental value', 'Práce je pro mě primárně prostředek k finančnímu zajištění.', true, 60),
('D6.1', 'd6_ai_readiness', 'Early adoption', 'Rád/a zkouším nové technologie a nástroje hned jak se objeví.', false, 61),
('D6.2', 'd6_ai_readiness', 'Familiarity preference', 'Preferuji nástroje a postupy které už dobře znám.', true, 62),
('D6.3', 'd6_ai_readiness', 'Learning enthusiasm', 'Učení nových věcí mě baví a vnímám to jako příležitost.', false, 63),
('D6.4', 'd6_ai_readiness', 'Learning resistance', 'Učit se nové věci mě stresuje a raději se držím toho co umím.', true, 64),
('D6.5', 'd6_ai_readiness', 'Ambiguity tolerance', 'Dokážu pracovat efektivně i v nejistém prostředí bez jasných pravidel.', false, 65),
('D6.6', 'd6_ai_readiness', 'Clarity need', 'Nejistota a nejasnost mě znervózňuje a potřebuji jasné směřování.', true, 66),
('D6.7', 'd6_ai_readiness', 'AI engagement', 'Aktivně experimentuji s AI nástroji (ChatGPT Midjourney Copilot).', false, 67),
('D6.8', 'd6_ai_readiness', 'AI unfamiliarity', 'S AI nástroji nemám zkušenost a nejsem si jistý/á jak je používat.', true, 68),
('D6.9', 'd6_ai_readiness', 'AI awareness', 'Zajímá mě jak AI změní můj obor a aktivně se o tom vzdělávám.', false, 69),
('D6.10', 'd6_ai_readiness', 'Tech anxiety', 'Technologické změny v mém oboru mě spíše znepokojují.', true, 70),
('D6.11', 'd6_ai_readiness', 'Adaptation speed', 'Rychle se adaptuju na nové systémy a postupy v práci.', false, 71),
('D6.12', 'd6_ai_readiness', 'Adaptation time', 'Potřebuji čas na zvyknutí si na nové pracovní postupy.', true, 72)
ON CONFLICT (id) DO UPDATE SET
  dimension = EXCLUDED.dimension,
  subdimension = EXCLUDED.subdimension,
  prompt = EXCLUDED.prompt,
  reverse_scoring = EXCLUDED.reverse_scoring,
  sort_order = EXCLUDED.sort_order;


INSERT INTO public.job_role_profiles (title, d1, d2, d3, d4, d5, d6, salary_range, growth_potential, ai_impact, remote_friendly) VALUES
('AI Research Scientist', 6.60, 3.20, 6.00, 4.80, 5.50, 6.80, '120-220k CZK', 'High', 'Augmentation', 'Hybrid'),
('Machine Learning Engineer', 6.20, 4.10, 5.70, 4.70, 5.20, 6.40, '90-180k CZK', 'High', 'Augmentation', 'Hybrid'),
('Data Scientist', 6.10, 4.00, 5.60, 4.50, 5.10, 6.00, '90-160k CZK', 'High', 'Augmentation', 'Hybrid'),
('Data Engineer', 6.00, 3.80, 5.20, 4.60, 4.80, 5.80, '85-150k CZK', 'High', 'Augmentation', 'Hybrid'),
('Backend Engineer', 5.90, 3.80, 5.30, 4.70, 4.80, 5.80, '80-150k CZK', 'High', 'Augmentation', 'Hybrid'),
('Frontend Engineer', 5.50, 4.30, 5.10, 4.60, 5.20, 5.40, '70-140k CZK', 'High', 'Augmentation', 'Remote'),
('Full Stack Engineer', 5.70, 4.20, 5.20, 4.80, 5.00, 5.60, '80-150k CZK', 'High', 'Augmentation', 'Hybrid'),
('DevOps Engineer', 5.80, 4.10, 5.10, 5.10, 4.90, 6.00, '90-170k CZK', 'High', 'Augmentation', 'Hybrid'),
('Cybersecurity Analyst', 5.70, 4.10, 5.10, 4.60, 5.30, 5.60, '80-150k CZK', 'High', 'Transformation', 'Hybrid'),
('Product Manager', 5.10, 5.80, 5.30, 4.80, 5.60, 5.10, '90-170k CZK', 'High', 'Transformation', 'Hybrid'),
('Project Manager', 4.80, 5.60, 4.90, 4.70, 5.20, 4.80, '75-140k CZK', 'Medium', 'Transformation', 'Hybrid'),
('UX Designer', 4.90, 5.40, 5.20, 4.30, 5.80, 4.70, '70-140k CZK', 'Medium', 'Augmentation', 'Hybrid'),
('UX Researcher', 5.10, 5.50, 5.40, 4.20, 6.00, 4.80, '70-130k CZK', 'Medium', 'Augmentation', 'Remote'),
('Sales Manager', 4.10, 6.40, 5.80, 5.60, 5.30, 4.20, '80-150k CZK', 'Medium', 'Transformation', 'Hybrid'),
('Uklízečka / Uklízeč', 3.20, 4.50, 4.00, 3.80, 4.60, 3.00, '30-45k CZK', 'Low', 'At Risk', 'Onsite'),
('Údržbář / Technik údržby', 4.40, 3.80, 4.40, 4.30, 4.60, 3.60, '35-55k CZK', 'Medium', 'Augmentation', 'Onsite'),
('Skladník', 3.80, 4.00, 4.10, 4.20, 4.40, 3.40, '30-45k CZK', 'Low', 'At Risk', 'Onsite'),
('Řidič / Kurýr', 3.60, 3.90, 4.20, 4.40, 4.30, 3.50, '30-55k CZK', 'Medium', 'Transformation', 'Onsite'),
('Pokladní', 3.40, 5.20, 4.00, 3.90, 4.50, 3.20, '28-40k CZK', 'Low', 'At Risk', 'Onsite'),
('Prodavač / Prodejní asistent', 3.80, 5.80, 4.60, 4.30, 4.80, 3.80, '30-50k CZK', 'Medium', 'Transformation', 'Onsite'),
('Kuchař', 3.90, 4.40, 4.60, 5.00, 4.70, 3.40, '35-55k CZK', 'Medium', 'At Risk', 'Onsite'),
('Číšník / Servírka', 3.50, 5.80, 4.50, 4.60, 4.80, 3.40, '28-45k CZK', 'Medium', 'At Risk', 'Onsite'),
('Recepční', 3.70, 5.60, 4.40, 4.00, 4.70, 3.60, '30-45k CZK', 'Medium', 'Augmentation', 'Onsite'),
('Bezpečnostní pracovník', 3.90, 4.20, 4.30, 4.50, 4.50, 3.50, '30-45k CZK', 'Low', 'At Risk', 'Onsite'),
('Zdravotní sestra', 4.40, 6.00, 5.00, 4.80, 5.80, 4.20, '45-70k CZK', 'High', 'Augmentation', 'Onsite'),
('Lékař', 5.60, 5.20, 5.20, 5.00, 5.70, 5.00, '80-180k CZK', 'High', 'Augmentation', 'Onsite'),
('Pečovatel / Sociální pracovník', 4.00, 6.20, 4.80, 4.60, 5.90, 3.80, '32-50k CZK', 'High', 'Augmentation', 'Onsite'),
('Učitel', 4.60, 6.00, 5.20, 4.30, 5.80, 4.40, '40-70k CZK', 'High', 'Augmentation', 'Onsite'),
('Lektor / Trenér', 4.50, 6.00, 5.30, 4.40, 5.60, 4.60, '40-80k CZK', 'High', 'Augmentation', 'Hybrid'),
('Administrativní pracovník', 4.20, 4.80, 4.40, 4.00, 4.70, 4.00, '30-50k CZK', 'Medium', 'Transformation', 'Onsite'),
('Asistent / Asistentka', 4.10, 5.20, 4.50, 4.20, 4.80, 4.10, '30-55k CZK', 'Medium', 'Transformation', 'Hybrid'),
('Účetní', 5.00, 4.20, 4.60, 4.10, 4.80, 4.20, '40-70k CZK', 'Medium', 'Transformation', 'Hybrid'),
('Finanční specialista', 5.40, 4.40, 4.80, 4.20, 4.90, 4.50, '50-90k CZK', 'Medium', 'Augmentation', 'Hybrid'),
('HR Specialist', 4.30, 5.80, 4.90, 4.20, 5.60, 4.20, '45-80k CZK', 'Medium', 'Transformation', 'Hybrid'),
('Marketing Specialist', 4.60, 5.40, 5.00, 4.50, 5.30, 4.70, '45-85k CZK', 'Medium', 'Augmentation', 'Hybrid'),
('PR Specialist', 4.20, 5.90, 4.90, 4.30, 5.40, 4.30, '40-80k CZK', 'Medium', 'Augmentation', 'Hybrid'),
('Projektant / Inženýr', 5.20, 4.60, 5.00, 4.50, 4.90, 4.80, '60-110k CZK', 'Medium', 'Augmentation', 'Onsite'),
('Strojní inženýr', 5.40, 4.30, 4.90, 4.60, 4.80, 4.60, '60-110k CZK', 'Medium', 'Augmentation', 'Onsite'),
('Elektrotechnik', 5.00, 4.10, 4.80, 4.70, 4.80, 4.50, '55-100k CZK', 'Medium', 'Augmentation', 'Onsite'),
('Stavař / Stavbyvedoucí', 4.80, 5.00, 4.80, 5.20, 5.00, 4.10, '55-110k CZK', 'Medium', 'Transformation', 'Onsite'),
('Logistik', 4.70, 4.60, 4.70, 4.60, 4.80, 4.40, '45-85k CZK', 'Medium', 'Augmentation', 'Hybrid'),
('Nákupčí', 4.40, 5.10, 4.80, 4.40, 4.90, 4.30, '45-85k CZK', 'Medium', 'Transformation', 'Hybrid'),
('Quality Manager', 5.00, 4.60, 4.90, 4.50, 4.90, 4.60, '60-110k CZK', 'Medium', 'Augmentation', 'Hybrid'),
('Operations Manager', 4.90, 5.20, 4.90, 5.00, 5.10, 4.70, '80-140k CZK', 'Medium', 'Augmentation', 'Hybrid'),
('Plant Manager', 5.00, 5.00, 4.90, 5.10, 5.00, 4.50, '90-160k CZK', 'Medium', 'Transformation', 'Onsite'),
('Store Manager', 4.40, 5.80, 4.70, 4.80, 4.90, 4.00, '45-80k CZK', 'Medium', 'Transformation', 'Onsite'),
('General Manager', 5.20, 6.20, 5.40, 5.10, 5.40, 5.00, '120-220k CZK', 'High', 'Transformation', 'Hybrid'),
('CEO', 5.60, 6.50, 5.60, 5.20, 5.60, 5.50, '200-500k CZK', 'High', 'Transformation', 'Hybrid'),
('CFO', 5.80, 5.20, 5.20, 4.70, 5.00, 5.00, '180-400k CZK', 'High', 'Augmentation', 'Hybrid'),
('COO', 5.40, 6.00, 5.30, 5.30, 5.30, 5.00, '180-400k CZK', 'High', 'Transformation', 'Hybrid')
ON CONFLICT DO NOTHING;
