import { DEFAULT_JHI_PREFERENCES } from '../utils/jhiCalculator';
import { createDefaultTaxProfile } from '../services/taxEngine';
import type {
  CalendarEvent,
  CandidateInsight,
  CandidatePreferenceProfile,
  Company,
  HandshakeBlueprint,
  Role,
} from './models';

export const companies: Company[] = [
  {
    id: 'lumina',
    name: 'Lumina Labs',
    tagline: 'AI products that hold together even in real-world operation.',
    domain: 'AI Infrastructure',
    headquarters: 'Prague, CZ',
    narrative: 'Lumina builds AI-first product layers for companies that need reliable operation even in the mess of the real world.',
    coverImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1400&auto=format&fit=crop',
    logo: 'https://images.unsplash.com/photo-1545239351-1141bd82e8a6?q=80&w=200&auto=format&fit=crop',
    gallery: [],
    handshakeMaterials: [],
    theme: {
      primary: '#2450a6',
      secondary: '#dce8ff',
      accent: '#2f7ef6',
      surface: '#f6f9ff',
      glow: '36,80,166',
    },
    reviewer: {
      name: 'Sarah Chen',
      role: 'Lead Culture Architect',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=400&auto=format&fit=crop',
      intro: 'We are not looking for checked boxes. We are interested in judgment, energy and the way you enter real work.',
      meetingLabel: 'Coffee & Culture',
      durationMinutes: 15,
      tool: 'Google Meet',
    },
  },
  {
    id: 'ether',
    name: 'Ether Orbit',
    tagline: 'Distributed systems for the next generation of critical infrastructure.',
    domain: 'Protocol Systems',
    headquarters: 'Brno, CZ',
    narrative: 'Ether Orbit builds resilient infrastructure with an emphasis on systems thinking and architectural discipline.',
    coverImage: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?q=80&w=1400&auto=format&fit=crop',
    logo: 'https://images.unsplash.com/photo-1511367461989-f85a21fda167?q=80&w=200&auto=format&fit=crop',
    gallery: [],
    handshakeMaterials: [],
    theme: {
      primary: '#1f4b99',
      secondary: '#dce6ff',
      accent: '#3f78dd',
      surface: '#f5f8ff',
      glow: '31,75,153',
    },
    reviewer: {
      name: 'Marcus Chen',
      role: 'Head of Engineering',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&auto=format&fit=crop',
      intro: 'We use Handshake to see how you work with ambiguity before the first interview.',
      meetingLabel: 'Technical Debrief',
      durationMinutes: 30,
      tool: 'Google Meet',
    },
  },
];

export const blueprints: HandshakeBlueprint[] = [
  {
    id: 'bp-ai-design',
    name: 'AI Design Dialogue',
    roleFamily: 'design',
    tone: 'human',
    overview: 'Portfolio-backed journey with identity, motivation, alignment and cultural scheduling.',
    benchmarkLabels: ['User empathy', 'Systems thinking', 'Collaboration'],
    aiGeneratorNote: 'AI composes a low-friction narrative journey with proof and reflection instead of a generic cover letter.',
    scheduleEnabled: true,
    steps: [
      { id: 'identity', type: 'identity', title: 'Identity', prompt: 'Tell us who you are beyond the CV.', helper: 'Name, alias and the short human context behind your work.', required: true, uiVariant: 'split_form' },
      { id: 'motivation', type: 'motivation', title: 'Motivation', prompt: 'What draws you to this mission right now?', helper: 'We value specificity over polished language.', required: true, uiVariant: 'story_field' },
      { id: 'alignment', type: 'skill_alignment', title: 'Skill Alignment', prompt: 'Where do you see your next leap?', helper: 'Mark the areas where your profile already resonates and where you want to stretch.', required: true, uiVariant: 'signal_matrix' },
      { id: 'proof', type: 'portfolio_or_proof', title: 'Portfolio Proof', prompt: 'Show one relevant artifact or decision that represents your thinking.', helper: 'A link, product, process or case reflection is enough.', required: true, uiVariant: 'story_field' },
      { id: 'results', type: 'results_summary', title: 'Results', prompt: 'Interpret the signal.', helper: 'We translate your responses into recruiter-visible strengths and next-step guidance.', required: true, uiVariant: 'result_panel' },
      { id: 'schedule', type: 'schedule_request', title: 'Schedule', prompt: 'Pick the human next step.', helper: 'A lightweight conversation with the reviewer.', required: true, uiVariant: 'scheduler' },
    ],
  },
  {
    id: 'bp-protocol',
    name: 'Protocol Systems Assessment',
    roleFamily: 'engineering',
    tone: 'technical',
    overview: 'Architectural handshake with scenario, workspace and structured reflection.',
    benchmarkLabels: ['Scalability', 'Protocol logic', 'Execution quality'],
    aiGeneratorNote: 'AI generates a realistic challenge brief, reviewer rubric and concise follow-up prompts for technical judgment.',
    scheduleEnabled: true,
    steps: [
      { id: 'identity', type: 'identity', title: 'Identity', prompt: 'Enter the space as yourself, not as a PDF.', helper: 'Add legal name, working alias and one paragraph of context.', required: true, uiVariant: 'split_form' },
      { id: 'motivation', type: 'motivation', title: 'Motivation', prompt: 'Why this systems problem?', helper: 'Tell us what makes the architectural tension interesting to you.', required: true, uiVariant: 'story_field' },
      { id: 'workspace', type: 'task_workspace', title: 'Assessment Workspace', prompt: 'Respond to the system challenge.', helper: 'This can be code, pseudo-code or a structured technical answer.', required: true, uiVariant: 'workspace' },
      { id: 'reflection', type: 'reflection', title: 'Reflection', prompt: 'What tradeoff did you choose and why?', helper: 'We care about judgment, not just output.', required: true, uiVariant: 'story_field' },
      { id: 'results', type: 'results_summary', title: 'Results', prompt: 'Signal summary', helper: 'Performance criteria and reviewer note.', required: true, uiVariant: 'result_panel' },
      { id: 'schedule', type: 'schedule_request', title: 'Schedule', prompt: 'Open the next technical step.', helper: 'Book a focused review conversation.', required: true, uiVariant: 'scheduler' },
    ],
  },
];

export const roles: Role[] = [
  {
    id: 'lumina-product-design',
    companyId: 'lumina',
    title: 'Senior Product Designer & Systems Architect',
    team: 'Candidate Experience',
    location: 'Prague, CZ',
    countryCode: 'CZ',
    workModel: 'Hybrid',
    source: 'curated',
    roleFamily: 'design',
    level: 'Senior',
    salaryFrom: 105000,
    salaryTo: 145000,
    currency: 'CZK',
    heroImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=1200&auto=format&fit=crop',
    summary: 'Shape a candidate OS where premium storytelling and rigorous decision support meet.',
    challenge: 'Redesign the bridge between marketplace discovery and recruiter trust so the product feels premium, precise and human.',
    mission: 'Transform first contact into a branded dialogue instead of a generic apply form.',
    firstStep: 'Show how you would turn a role card into the start of a meaningful conversation.',
    description: 'Shape a candidate operating system where discovery, trust, and product craft meet in one coherent experience. You will work across role cards, recruiter signals, and the first moments of candidate engagement.',
    skills: ['Product design', 'Design systems', 'Candidate experience', 'Systems thinking'],
    benefits: ['Hybrid setup', 'Learning budget', '5 weeks of vacation', 'Mentorship'],
    coordinates: { lat: 50.0755, lng: 14.4378 },
    blueprintId: 'bp-ai-design',
    featuredInsights: ['Portfolio-backed handshake', 'Visible design rationale', 'Fast human follow-up'],
  },
  {
    id: 'ether-protocol-architect',
    companyId: 'ether',
    title: 'Senior Protocol Architect',
    team: 'Core Network',
    location: 'Brno, CZ',
    countryCode: 'CZ',
    workModel: 'Hybrid',
    source: 'curated',
    roleFamily: 'engineering',
    level: 'Lead',
    salaryFrom: 5200,
    salaryTo: 6900,
    currency: 'EUR',
    heroImage: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?q=80&w=1200&auto=format&fit=crop',
    summary: 'Lead protocol evolution for a resilient distributed system at critical scale.',
    challenge: 'Design a resilient synchronization strategy for high-frequency node discovery under cross-region latency.',
    mission: 'Move protocol decisions from local optimization to system-level robustness.',
    firstStep: 'Respond to the protocol brief and explain one architectural tradeoff you would defend in a review.',
    description: 'Lead protocol evolution for a distributed network that needs to stay stable under high-throughput coordination pressure. The role combines system design, reviewer communication, and practical execution judgment.',
    skills: ['Distributed systems', 'Rust', 'System design', 'Security'],
    benefits: ['Remote days', 'Research budget', '13th salary', 'Conference travel'],
    coordinates: { lat: 49.1951, lng: 16.6068 },
    blueprintId: 'bp-protocol',
    featuredInsights: ['Architectural reasoning', 'Reviewer note', 'Benchmarked performance signals'],
  },
  {
    id: 'import-berlin-ml-platform',
    companyId: 'lumina',
    title: 'Machine Learning Platform Engineer',
    team: 'Imported Opportunity',
    location: 'Berlin, DE',
    countryCode: 'DE',
    workModel: 'Hybrid',
    source: 'imported',
    roleFamily: 'engineering',
    level: 'Senior',
    salaryFrom: 6400,
    salaryTo: 7800,
    currency: 'EUR',
    heroImage: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=1200&auto=format&fit=crop',
    summary: 'External opportunity discovered from the market feed. Strong fit, but the next step stays outside Jobshaman.',
    challenge: 'Prepare your narrative before you leave the platform: why this team, why this stack, why now.',
    mission: 'Imported role for outbound acceleration.',
    firstStep: 'Use the prep surface to sharpen your first outreach before opening the source listing.',
    description: 'External ML platform role discovered through the marketplace feed. Use Jobshaman to evaluate fit, sharpen your positioning, and prepare a stronger outbound move before leaving the platform.',
    outboundUrl: 'https://example.com/jobs/ml-platform-engineer',
    importedNote: 'This role stays external. Jobshaman helps you prepare, not replace the company process.',
    skills: ['Python', 'ML infrastructure', 'Kubernetes', 'Platform engineering'],
    benefits: ['Remote days', 'Stock options', 'Education budget'],
    coordinates: { lat: 52.52, lng: 13.405 },
    featuredInsights: ['Cross-border fit', 'Prep before outbound', 'Commute and tax reality'],
  },
  {
    id: 'import-vienna-care-ops',
    companyId: 'lumina',
    title: 'Operations Lead for Care Delivery',
    team: 'Imported Opportunity',
    location: 'Vienna, AT',
    countryCode: 'AT',
    workModel: 'On-site',
    source: 'imported',
    roleFamily: 'operations',
    level: 'Senior',
    salaryFrom: 4300,
    salaryTo: 5200,
    currency: 'EUR',
    heroImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1200&auto=format&fit=crop',
    summary: 'High-responsibility imported role suitable for cross-border exploration.',
    challenge: 'Assess whether the operating tempo, salary reality and commute pattern actually fit your life.',
    mission: 'Imported role for real-world evaluation and outbound follow-through.',
    firstStep: 'Review the operating reality, then step out with a sharper hypothesis.',
    description: 'External operations role with meaningful delivery responsibility. The prep flow helps evaluate work model, cross-border practicality, and whether the role matches real-life constraints before outbound follow-up.',
    outboundUrl: 'https://example.com/jobs/care-ops-lead',
    importedNote: 'Use Jobshaman to test fit against your real constraints before going outbound.',
    skills: ['Operations', 'Leadership', 'Care delivery', 'Process design'],
    benefits: ['Relocation support', 'Meal vouchers', 'Leadership coaching'],
    coordinates: { lat: 48.2082, lng: 16.3738 },
    featuredInsights: ['Cross-border opportunity', 'Real-life fit', 'Outbound prep'],
  },
];

export const candidateDefaultPreferences: CandidatePreferenceProfile = {
  name: 'Jordan Doe',
  legalName: 'Jordan Doe',
  preferredAlias: 'Jordan',
  story: 'I am looking for roles where structured thinking, humane communication and a realistic next leap all meet in one place.',
  address: 'Prague, CZ',
  coordinates: { lat: 50.0755, lon: 14.4378 },
  transportMode: 'public',
  commuteFilterEnabled: true,
  commuteToleranceMinutes: 80,
  borderSearchEnabled: true,
  searchRadiusKm: 35,
  taxProfile: createDefaultTaxProfile('CZ'),
  jhiPreferences: DEFAULT_JHI_PREFERENCES,
  portfolioUrl: 'https://portfolio.design/jordan',
  linkedInUrl: 'https://linkedin.com/in/jordandoe',
};

export const talentPool: CandidateInsight[] = [
  {
    id: 'cand-elena',
    candidateName: 'Elena Rodriguez',
    headline: 'Senior Product Designer & Systems Architect',
    location: 'San Francisco, CA',
    matchPercent: 94,
    verifiedScore: 98,
    topSignals: ['Design systems clarity', 'Technical translation', 'Decision quality'],
    recommendation: 'Move to next stage. Candidate shows strong synthesis and exceptional structure under ambiguity.',
    internalNote: 'Elena demonstrated an exceptional ability to map technical constraints to design solutions during the whiteboard session.',
    skills: [
      { label: 'Design Systems', score: 94, tags: ['React architecture', 'Token mgmt', 'Documentation'] },
      { label: 'User Research', score: 82, tags: ['A/B testing', 'Interviews'] },
      { label: 'Product Strategy', score: 78, tags: ['Roadmapping', 'KPIs'] },
    ],
  },
  {
    id: 'cand-marcus',
    candidateName: 'Marcus Chen',
    headline: 'Protocol Staff Engineer',
    location: 'Brno, CZ',
    matchPercent: 89,
    verifiedScore: 94,
    topSignals: ['Protocol depth', 'Scalability modeling', 'Execution speed'],
    recommendation: 'Book technical review. High systems confidence with strong benchmark evidence.',
    internalNote: 'Protocol reasoning was unusually concise and resilient under review pressure.',
    skills: [
      { label: 'Protocol Logic', score: 98, tags: ['Rust', 'Consensus', 'Latency'] },
      { label: 'Scalability', score: 89, tags: ['Load modeling', 'Failure modes'] },
      { label: 'Security', score: 92, tags: ['Signatures', 'Recovery'] },
    ],
  },
  {
    id: 'cand-sarah',
    candidateName: 'Sarah J. Miller',
    headline: 'AI Engineer',
    location: 'Prague, CZ',
    matchPercent: 87,
    verifiedScore: 91,
    topSignals: ['Transformer depth', 'Experiment design', 'Learning speed'],
    recommendation: 'Keep warm and align to the strongest role lane. Candidate is highly trainable and aligned.',
    internalNote: 'Could be ideal for the AI design bridge role if we value collaboration as much as raw implementation speed.',
    skills: [
      { label: 'ML Systems', score: 91, tags: ['PyTorch', 'Transformers'] },
      { label: 'Experimentation', score: 86, tags: ['Benchmarks', 'Evaluation'] },
      { label: 'Communication', score: 84, tags: ['Docs', 'Cross-team'] },
    ],
  },
];

export const recruiterCalendar: CalendarEvent[] = [
  { id: 'event-1', title: 'Review 5 new applications', stage: 'initial', day: 4, time: '09:00', note: 'Frontend Developer' },
  { id: 'event-2', title: 'Evaluation of technical task', stage: 'assessment', day: 7, time: '09:30', note: 'Ether Orbit' },
  { id: 'event-3', title: 'Panel interview', stage: 'panel', day: 7, time: '16:00', note: 'Lumina' },
  { id: 'event-4', title: 'Final offer alignment', stage: 'offer', day: 18, time: '13:30', note: 'Decision window' },
];
